
<div class="container-fluid">
        <div>
            <p style="padding-left: 10px;">Gestione abilitazione / disabilitazione CANALI per associazione prodotto in vetrina <strong>(per associare un prodotto bisogna abilitare almeno un canale)</strong></p>
        </div>

    <div class="card">
        <form name="canali_esercente" action="?page=esercenti_macchine_canali" method="post"> 
              <div class="row">
                     <label for="iva_id" class="col-sm-2 col-form-label text-end">Seleziona la macchina</label>
                     <div class="col-sm-3">
                            <select name="macchina_id" id="macchina_id" class="form-select" aria-label="Default select example">
                                 <option value="0">SELEZIONA</option>
                                    <?php foreach( $elenco_macchine as $row_macchina) {
                                                            $id_macchina = $row_macchina["id"];  
                                                            $matricola =  $row_macchina["matricola"];
                                                            $tipologia_id_macchina =  $row_macchina["tipologia_id"];

                                                            if ($id_macchina == $_POST['macchina_id']) {
                                                                $selected = "selected";
                                                            } else {
                                                                $selected = "";
                                                            }
                                    ?>
                                        <option <?= $selected; ?> value="<?= $id_macchina; ?>"><?= $matricola; ?></option>
                                    <?php } ?>                 
                              </select>
                    </div>

                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-success ">RICERCA</button>
                    </div>
                    <div class="col-sm-2">
                        <a href="?page=esercenti_macchine_canali" class="btn btn-danger">RESET FILTRI</a>
                    </div>
                </div>
        
        </form>
    </div>
    <div class="card mb-4">
        
<?php  

                echo $xcrud->render(); 
     
 ?>
    </div> 
</div>
   
   