   <div class="bg-light  d-flex flex-row align-items-center">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="clearfix">
              <h1 class=" text-center">RISULTATO INSERIMENTO</h1>
              <br />
              
             
            </div>
          <h4 class="pt-3 text-center text-success"><?= $messaggio; ?></h4>
         
          </div>
           
        </div>
      </div>
    </div>
   